### PR TITLE
Feature/prop management refactor/aidan

### PR DESCRIPTION
**Pull request by aidanamato**
I'm still going through the components but I wanted to get a PR in before a lot of people clone this repo so they have as up to date code as possible.

### CODE REVIEW

**Review by wij2012 — APPROVED** [review]
Some reorganization and mild refactoring. Should be good to go for a merge. - Will

**Review by RyanOdeneal — APPROVED** [review]
hey its me approving it

**Review by RyanOdeneal — CHANGES_REQUESTED** [review]
hey I want changes

**Review by RyanOdeneal — APPROVED** [review]
hey im approving it again

**Review by wij2012 — APPROVED** [review]
ANother approval

**Pull request merged**
